sudo: false
language: python
python: 3.7
script:
- "./test.sh"
- "./build.sh"
deploy:
  provider: pypi
  skip_cleanup: true
  user: bigclownlabs
  on:
    tags: true
  password:
    secure: oHMEjEjXKM9zWnRGLKzZ1NVRHg9f3Nrh/A9CD6T4Kw3boljeKw9PsPPu0fUaG+1cuJA7EZnQ4OruXlhEnlS7i/ElMqUz7c02/DW34gFFMezyGZ/Wv4o0NvDVZXVYk91hrxTqWhP2dKIt1rfKyqWwyuBDX/LYxTdrxUbQfonLFfNUckupD5fekx7Vgovl7KcSHHKXX3dpp2RL8ofIXrFwsPCNB1TYgN19Vke/0fxUTq7MzqrfhFtCtmAVqW06CMP18cTgeTeISjkgXws7yY7a+JJsZJSsa0mi+dYZUrrsbQrWdoj9szNPtPOVO/vJsnPlWKjceCwMMKTGuvZrs3OI5WVshjoyouc+uWx8mj2t+wEyXAZk4DpQ+KI+JDM94YqlRkTQsi29CP6h1vT3jM783AYpMfauR9WzsnPp1Okj7Kls7g0smXdd7BQaii5sD4FKWIqWQh2h2NgpzRMFBh3miMkospSTFoHn4cHMSOgphejbvDvdQvWDwYFKf87SlPW+8zx6yyXsSgUWtfMl4F+t2nSEiUSNVfPGWovjzBS7hE4v0stiJyXo6QUsdBZ4wEjMunKOICUwVGxB6MAyXfhz2IORnqhMg86eoA0YHXVQ/f+60dVip6QsNQaktgtCE2yVgjCWaVWR79ngoPyw8TCenfkg4IBMJwPgObQLQi5Yg5Y=
