sudo: false
language: python
python: 3.4
script:
- "./script/test"
- "./script/build"
deploy:
  provider: pypi
  skip_cleanup: true
  user: bigclownlabs
  password:
    secure: fnGbFMzx757fpJ0jo6ZQ7Szj8OdG7MOEnfWrSkvj9cG9UZjvExog/1v31uuTGUwXfMwtQkDI4gdWXTfq89KxM6KcLyAXTDQj4uRXvxXSLzYN+iUE0F+q2uGSmHsJAXRrfdE5b1GXK3UBKjScJLGgopBr9ReufeMVjPJgCy+qWSs9+Ebl+9lzXVlcldNnt76LSJB6XdmkkNjQR0yzqnuDE8DcGsLw0zU322ZlEb6GZevSagPUb9kPnVNDWzKbdzVsMm35dcfc0C3lBk4dPJSMn/EFO0v7z84D0PB5b25Vk0Ozi4k5q1pYene3GKMKYcoKhe+PdMHMsW/IxcLtzBxGqTmFZnXAVDkGU6R1cFLyEycVzyi8uulUVMHG9FVPNW5/AbHp+OSDHOJFP4RdOCl8+6IjXX0nWasGXZakF3+rNlaXDQXg8K08aeJ8qPpYZDWWCUr1K5JaBsj1T+5nOB+e2znaeo9AmsQ7ePolkSr5VZsvI/oVDHHJ0yTUdNghvMfeWiNaGXFW79HMdUwzVTtLeTpRqotu+E8CMTZxPd8NuiSz0m6x8FeL3bmG36SWTsF5UNRrTADvd2wtrqUQ1KSFYqfc9b6GWbnKrJAW4QQ0O1Pwvx7GqJ/ZM9QvRYDrS4AEE2atMl+K19AyTdAz4qVerQkIy/FwWR9UdSCLPzvJQjs=
  on:
    tags: true
