mqtt:
  host: 127.0.0.1
  port: 1883

influxdb:
  host: 127.0.0.1
  port: 8086
  database: node

http:
  destination: https://example.com/content
  action: post
  username: username
  password: password

base64decode:
  source: $.payload.data
  target: data

points:
  - measurement: temperature
    database: my_database
    topic: node/+/thermometer/+/temperature
    fields:
      value: $.payload.data
      decodedvalue: $.base64decoded.data.hex
      foo: 
        value: $.payload.foo
        type: "float"
    tags:
      id: $.topic[1]
      channel: $.topic[3]
    httpcontent:
      frame: $.base64decoded.data.hex
      skipBytes: "1"